#include <stdint.h> // for uint8_t, uint32_t, uint64_t

#define APIENTRY WINAPI
#define CALLBACK __stdcall
#define CONST const
#define VOID void
#define POINTER_SIGNED __sptr
#define POINTER_UNSIGNED __uptr
#define WINAPI __stdcall
#define POINTER_32 __ptr32
#define POINTER_64 __ptr64

typedef wchar_t WCHAR;
typedef double LONGLONG;
typedef uint64_t ULONG_PTR;
typedef uint64_t ULONGLONG;
typedef uint64_t LONG_PTR; 
typedef unsigned char UCHAR;
typedef uint64_t INT_PTR; 
typedef int HALF_PTR;
typedef uint64_t UINT_PTR;
typedef unsigned int UINT;
typedef unsigned int UHALF_PTR;
typedef int BOOL;
typedef unsigned char BYTE;
typedef char CCHAR;
typedef char CHAR;
typedef unsigned long DWORD;
typedef uint64_t DWORDLONG;
typedef unsigned int DWORD32;
typedef uint64_t DWORD64;
typedef float FLOAT;
typedef int HFILE;
typedef int INT;
typedef signed char INT8;
typedef signed short INT16;
typedef signed int INT32;
typedef int64_t INT64;
typedef long LONG;
typedef signed int LONG32;
typedef uint64_t LONG64;
typedef __nullterminated CONST CHAR *LPCSTR;
typedef int *LPINT;
typedef long *LPLONG;
typedef void *LPVOID;
typedef int *PINT;
typedef short SHORT;
typedef void *PVOID;
typedef uint64_t QWORD;
typedef unsigned char UINT8;
typedef unsigned short UINT16;
typedef unsigned int UINT32;
typedef uint64_t UINT64;
typedef unsigned long ULONG;
typedef unsigned int ULONG32;
typedef uint64_t ULONG64;
typedef const UNICODE_STRING *PCUNICODE_STRING;
typedef unsigned short USHORT;
typedef unsigned short WORD;
typedef CONST void *LPCVOID;
typedef CONST WCHAR *LPCWSTR;
typedef LPCWSTR PCTSTR;
typedef LPWSTR LPTSTR;
typedef HALF_PTR *PHALF_PTR;
typedef UHALF_PTR *PUHALF_PTR;
typedef UCHAR *PUCHAR;
typedef LPWSTR PTSTR;
typedef WCHAR TCHAR;
typedef WORD ATOM;
typedef WCHAR TBYTE;
typedef BYTE BOOLEAN;
typedef DWORD COLORREF;
typedef ULONG_PTR DWORD_PTR;
typedef HANDLE HACCEL;
typedef PVOID HANDLE;
typedef HANDLE HBITMAP;
typedef HANDLE HBRUSH;
typedef HANDLE HCOLORSPACE;
typedef HANDLE HCONV;
typedef HANDLE HCONVLIST;
typedef HICON HCURSOR;
typedef HANDLE HDC;
typedef HANDLE HDDEDATA;
typedef HANDLE HDESK;
typedef HANDLE HDROP;
typedef HANDLE HDWP;
typedef HANDLE HENHMETAFILE;
typedef HANDLE HFONT;
typedef HANDLE HGDIOBJ;
typedef HANDLE HGLOBAL;
typedef HANDLE HHOOK;
typedef HANDLE HICON;
typedef HANDLE HINSTANCE;
typedef HANDLE HKEY;
typedef HANDLE HKL;
typedef HANDLE HLOCAL;
typedef HANDLE HMENU;
typedef HANDLE HMETAFILE;
typedef HINSTANCE HMODULE;
typedef HANDLE HMONITOR;
typedef HANDLE HPALETTE;
typedef HANDLE HPEN;
typedef LONG HRESULT;
typedef HANDLE HRGN;
typedef HANDLE HRSRC;
typedef HANDLE HSZ;
typedef HANDLE WINSTA;
typedef HANDLE HWND;
typedef WORD LANGID;
typedef DWORD LCID;
typedef DWORD LCTYPE;
typedef DWORD LGRPID;
typedef LONG_PTR LPARAM;
typedef BOOL far *LPBOOL;
typedef BYTE far *LPBYTE;
typedef DWORD *LPCOLORREF;
typedef DWORD *LPDWORD;
typedef HANDLE *LPHANDLE;
typedef CHAR *LPSTR;
typedef WORD *LPWORD;
typedef WCHAR *LPWSTR;
typedef LONG_PTR LRESULT;
typedef BOOL *PBOOL;
typedef BOOLEAN *PBOOLEAN;
typedef BYTE *PBYTE;
typedef CHAR *PCHAR;
typedef CONST CHAR *PCSTR;
typedef CONST WCHAR *PCWSTR;
typedef DWORD *PDWORD;
typedef DWORDLONG *PDWORDLONG;
typedef DWORD_PTR *PDWORD_PTR;
typedef DWORD32 *PDWORD32;
typedef DWORD64 *PDWORD64;
typedef FLOAT *PFLOAT;
typedef HANDLE *PHANDLE;
typedef HKEY *PHKEY;
typedef INT_PTR *PINT_PTR;
typedef INT8 *PINT8;
typedef INT16 *PINT16;
typedef INT32 *PINT32;
typedef INT64 *PINT64;
typedef PDWORD PLCID;
typedef LONG *PLONG;
typedef LONGLONG *PLONGLONG;
typedef LONG_PTR *PLONG_PTR;
typedef LONG32 *PLONG32;
typedef LONG64 *PLONG64;
typedef SHORT *PSHORT;
typedef SIZE_T *PSIZE_T;
typedef SSIZE_T *PSSIZE_T;
typedef CHAR *PSTR;
typedef TBYTE *PTBYTE;
typedef TCHAR *PTCHAR;
typedef UINT *PUINT;
typedef UINT_PTR *PUINT_PTR;
typedef UINT8 *PUINT8;
typedef UINT16 *PUINT16;
typedef UINT32 *PUINT32;
typedef UINT64 *PUINT64;
typedef ULONG *PULONG;
typedef ULONGLONG *PULONGLONG;
typedef ULONG_PTR *PULONG_PTR;
typedef ULONG32 *PULONG32;
typedef ULONG64 *PULONG64;
typedef USHORT *PUSHORT;
typedef WCHAR *PWCHAR;
typedef WORD *PWORD;
typedef WCHAR *PWSTR;
typedef HANDLE SC_HANDLE;
typedef LPVOID SC_LOCK;
typedef HANDLE SERVICE_STATUS_HANDLE;
typedef ULONG_PTR SIZE_T;
typedef LONG_PTR SSIZE_T;
typedef UNICODE_STRING *PUNICODE_STRING;
typedef LONGLONG USN;
typedef UINT_PTR WPARAM;
typedef struct _UNICODE_STRING {
    USHORT  Length;
    USHORT  MaximumLength;
    PWSTR  Buffer;
} UNICODE_STRING;